### ISSUE TITLE
Can't support on Python 3.5.1 ?

### ISSUE THREAD

**Issue by joway** [andward/AndwardTODO#1]
The error is : 

```
Exception:
Traceback (most recent call last):
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/commands/install.py", line 282, in run
    wheel_cache
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/basecommand.py", line 291, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/req/req_file.py", line 89, in parse_requirements
    for req in req_iter:
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/req/req_file.py", line 137, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/req/req_install.py", line 213, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/req/req_install.py", line 67, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
    reqs = list(parse_requirements(s))
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
    "version spec")
  File "/Users/joway/.pyenv/versions/3.5.1/envs/Andward/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pip._vendor.pkg_resources.RequirementParseError: Expected version spec in django=1.5.5 at =1.5.5
```

**Comment by andward** [comment]
I used Django version which only support <2.7....
